version: "3.9"

services:
    db:
        image: postgres:16
        container_name: anibento-db
        environment:
            POSTGRES_USER: anibento_user
            POSTGRES_PASSWORD: anibento_pw
            POSTGRES_DB: anibento
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data

    api:
        build:
            context: .
            dockerfile: AniBento.Api/Dockerfile
        container_name: anibento-api
        depends_on:
            - db
        env_file:
            - .env
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ConnectionStrings__DefaultConnection: Host=db;Database=anibento;Username=anibento_user;Password=anibento_pw
            Jwt__Key: ${JWT__KEY}
            ASPNETCORE_URLS: http://0.0.0.0:8080 # Bind to local network interfaces for development
        ports:
            - "5163:8080"

volumes:
    pg_data:
